import discord, os, random, json
from discord.ext import commands
from data.print import *

with open("./data/config.json", "r") as file:
    data = json.load(file)

emojis = [
    ":grinning:",
    ":smiley:",
    ":smile:",
    ":grin:",
    ":laughing:",
    ":sweat_smile:",
    ":joy:",
    ":rofl:",
    ":relaxed:",
    ":blush:",
    ":innocent:",
    ":slightly_smiling_face:",
    ":upside_down_face:",
    ":wink:",
    ":relieved:",
    ":heart_eyes:",
    ":kissing_heart:",
    ":kissing:",
    ":kissing_smiling_eyes:",
    ":kissing_closed_eyes:",
    ":yum:",
    ":stuck_out_tongue:",
    ":stuck_out_tongue_winking_eye:",
    ":stuck_out_tongue_closed_eyes:",
    ":money_mouth_face:",
    ":thinking:",
    ":zipper_mouth_face:",
    ":neutral_face:",
    ":expressionless:",
    ":no_mouth:",
    ":smirk:",
    ":unamused:",
    ":grimacing:",
    ":lying_face:",
    ":relieved:",
    ":pensive:",
    ":sleepy:",
    ":drooling_face:",
    ":sleeping:",
    ":mask:",
    ":face_with_thermometer:",
    ":face_with_head_bandage:",
    ":nauseated_face:",
    ":sneezing_face:",
    ":hot_face:",
    ":cold_face:",
    ":woozy_face:",
    ":dizzy_face:",
    ":exploding_head:",
    ":partying_face:",
    ":sunglasses:",
    ":nerd_face:",
    ":confused:",
    ":worried:",
    ":slightly_frowning_face:",
    ":frowning_face:",
    ":open_mouth:",
    ":hushed:",
    ":astonished:",
    ":flushed:",
    ":pleading_face:",
    ":frowning:",
    ":anguished:",
    ":fearful:",
    ":cold_sweat:",
    ":disappointed_relieved:",
    ":cry:",
    ":sob:",
    ":scream:",
    ":confounded:",
    ":persevere:",
    ":disappointed:",
    ":sweat:",
    ":weary:",
    ":tired_face:",
    ":yawning_face:",
    ":triumph:",
    ":rage:",
    ":angry:",
    ":smiling_imp:",
    ":imp:",
    ":skull:",
    ":skull_and_crossbones:",
    ":poop:",
    ":clown_face:",
    ":ogre:",
    ":goblin:",
    ":ghost:",
    ":alien:",
    ":space_invader:",
    ":robot:",
    ":jack_o_lantern:",
    ":smiley_cat:",
    ":smile_cat:",
    ":joy_cat:",
    ":heart_eyes_cat:",
    ":smirk_cat:",
    ":kissing_cat:",
    ":scream_cat:",
    ":crying_cat_face:",
    ":pouting_cat:",
    ":see_no_evil:",
    ":hear_no_evil:",
    ":speak_no_evil:",
    ":kiss:",
    ":love_letter:",
    ":cupid:",
    ":gift_heart:",
    ":sparkling_heart:",
    ":heartpulse:",
    ":heartbeat:",
    ":revolving_hearts:",
    ":two_hearts:",
    ":heart_decoration:",
    ":broken_heart:",
    ":heart:",
    ":orange_heart:",
    ":yellow_heart:",
    ":green_heart:",
    ":blue_heart:",
    ":purple_heart:",
    ":brown_heart:",
    ":black_heart:",
    ":white_heart:",
    ":100:",
    ":anger:",
    ":boom:",
    ":collision:",
    ":dizzy:",
    ":sweat_drops:",
    ":dash:",
    ":hole:",
    ":bomb:",
    ":speech_balloon:",
    ":eye_in_speech_bubble:",
    ":left_speech_bubble:",
    ":right_anger_bubble:",
    ":thought_balloon:",
    ":zzz:",
    ":wave:",
    ":raised_back_of_hand:",
    ":raised_hand_with_fingers_splayed:",
    ":vulcan_salute:",
    ":ok_hand:",
    ":pinched_fingers:",
    ":pinching_hand:",
    ":v:",
    ":love_you_gesture:",
    ":metal:",
    ":call_me_hand:",
    ":point_left:",
    ":point_right:",
    ":point_up_2:",
    ":point_down:",
    ":point_up:",
    ":raised_hand:",
    ":raised_hands:",
    ":clap:",
    ":handshake:",
    ":pray:",
    ":writing_hand:",
    ":nail_care:",
    ":selfie:",
    ":muscle:",
    ":mechanical_arm:",
    ":mechanical_leg:",
    ":leg:",
    ":foot:",
    ":ear:",
    ":ear_with_hearing_aid:",
    ":nose:",
    ":brain:",
    ":anatomical_heart:",
    ":lungs:",
    ":tooth:",
    ":bone:",
    ":eyes:",
    ":eye:",
    ":tongue:",
    ":lips:",
    ":baby:",
    ":child:",
    ":boy:",
    ":girl:",
    ":adult:",
    ":blond_haired_person:",
    ":man:",
    ":bearded_person:",
    ":man_with_probing_cane:",
    ":woman_with_probing_cane:",
    ":woman:"
    ":santa_tone5:"
]

class random_emoji(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_message(self, message):
        if message.author.id in data["whitelisted"]:
            if message.content == f"{data['prefix']}randomemoji":
                await message.reply(random.choice(emojis))
                os.system("cls"), print(logo()), print(login_box(self.bot.user)), print(output_text(f"[<>] `{data['prefix']}random emoji` has been successfully ran by {message.author}"))
    
    @commands.command()
    async def randomemoji(self, ctx):
        await ctx.message.delete()
        await ctx.send(random.choice(emojis))

async def setup(bot):
    await bot.add_cog(random_emoji(bot))